// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class mid_contentstatusadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mid_contentstatusadd));
        
        string IMigrationMetadata.Id
        {
            get { return "202105312258233_mid_contentstatusadd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
